name: Update Status Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate status site
        run: npx upptime@latest update-site
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
